[package]
name = "keyboard"
version = "0.1.0"
authors = ["barmovshovich"]
edition = "2018"

[dependencies]
midir = "0.5.0"
wmidi = "1.1.0"
pitch_calc = "0.11.1"
dimensioned = "0.7.0"
synth = "0.11.0"
portmidi = "0.2.4"
